name: movil2proyecto
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter  
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  drift: ^2.4.1  # Alternativa moderna a sqflite con mejor soporte multiplataforma



  path: ^1.9.1
  cupertino_icons: ^1.0.8

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_chocobite.jpg
